-- مخطط قاعدة بيانات Supabase المقترح لبوابة قرية الحرية
-- لا تضع مفتاح service_role داخل HTML أو GitHub.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  priority text not null default 'normal' check (priority in ('normal','urgent')),
  published boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text not null,
  phone text,
  location text,
  published boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  type text not null,
  body text not null,
  status text not null default 'new' check (status in ('new','reviewing','closed')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor uuid references auth.users(id),
  action text not null,
  table_name text,
  record_id bigint,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.announcements enable row level security;
alter table public.services enable row level security;
alter table public.complaints enable row level security;
alter table public.activity_logs enable row level security;

-- قراءة المحتوى المنشور للمستخدمين المسجلين.
create policy "read published announcements" on public.announcements
for select to authenticated using (published = true);

create policy "read published services" on public.services
for select to authenticated using (published = true);

-- يحتاج المشروع في الإصدار المتصل إلى دالة is_admin() SECURITY DEFINER
-- قبل تفعيل سياسات الكتابة التالية. مثال آمن:
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin');
$$;

create policy "admins manage announcements" on public.announcements
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "admins manage services" on public.services
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "users submit complaints" on public.complaints
for insert to authenticated with check (created_by=auth.uid());

create policy "admins read complaints" on public.complaints
for select to authenticated using (public.is_admin());

create policy "admins update complaints" on public.complaints
for update to authenticated using (public.is_admin()) with check (public.is_admin());


create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  enabled boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  kind text not null default 'normal' check (kind in ('normal','urgent')),
  published boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

create index if not exists announcements_created_at_idx on public.announcements(created_at desc);
create index if not exists services_category_idx on public.services(category);
create index if not exists complaints_status_idx on public.complaints(status);
create index if not exists notifications_created_at_idx on public.notifications(created_at desc);

alter table public.categories enable row level security;
alter table public.notifications enable row level security;
alter table public.settings enable row level security;

create policy "read enabled categories" on public.categories
for select to authenticated using (enabled = true);

create policy "admins manage categories" on public.categories
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "read published notifications" on public.notifications
for select to authenticated using (published = true);

create policy "admins manage notifications" on public.notifications
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "admins manage settings" on public.settings
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Default categories
insert into public.categories(name,icon,sort_order) values
('مساجد','🕌',1),('مدارس','🏫',2),('صحة','🏥',3),('طوارئ','🚑',4),
('بقاليات','🛒',5),('أفران','🥖',6),('صيدليات','💊',7),('أطباء','🩺',8),
('مهن وخدمات','🛠️',9),('مواصلات','🚐',10)
on conflict(name) do nothing;
